### ISSUE TITLE
[FEATURE] - run next job with delay after previous job finish

### ISSUE THREAD

**Issue by kuchaguangjie** [go-co-op/gocron#674] opened 2024-02-09 22:13 UTC
`Every(30).Seconds()` run every 30s. The 30s count from start of previous job, I think.

But the job might take a long time sometimes, I want the `30s` be end of previous job, not start of previous job.
Means if previous job takes 35s, then the next job will start 30s after it finish, so that they won't overlap.

Is there a method for that? Or, is there some existing tool to achieve the goal ?

**Comment by JohnRoesler** [comment] 2024-02-12 15:42
Duplicate of #565

**Closed as not planned by JohnRoesler** 2024-02-12 15:42 UTC
Labels: enhancement
