### ISSUE TITLE
[BUG] - All Jobs Start Immediately

### ISSUE THREAD

**Issue by graywolf336** [go-co-op/gocron#60] opened 2020-09-15 13:21 UTC
### Describe the bug
I have three jobs which I want to run at a specific time of day and a specific day of the month. None of them have `StartImmediately()` so I would not expect them to run whenever they get scheduled.

### To Reproduce

1. `scheduler.Every(1).Day().At("00:30").Do()`
1. Expect the job to not run
1. See the logs of the job running

### Version
`v0.3.1` from `go.mod` file

### Expected behavior
The expected behavior is that because I do not have `StartImmediately()` attached to it they would not run immediately at the start up and instead would only run at the times scheduled.

### Additional context
![Screen Shot 2020-09-15 at 8 17 09 AM](https://user-images.githubusercontent.com/850391/93215756-7a422b80-f72c-11ea-982a-40263ecd1b88.png)

**Comment by arjunmahishi** [comment] 2020-09-15 15:17
Hey @graywolf336, 
I am not able to reproduce this with the steps you have mentioned. Is it possible for you to paste the exact snippet of code here?

This is working fine for me:
```go
func main() {
    s := gocron.NewScheduler(time.Local)
    s.Every(3).Seconds().At("20:35").Do(func() {
        log.Println("DONE")
    })  
    log.Println("Starting..")
    <-s.StartAsync()
}
```
Output:
```bash
 $ go run main.go 
2020/09/15 20:46:02 Starting..
2020/09/15 20:46:05 DONE
2020/09/15 20:46:08 DONE
2020/09/15 20:46:11 DONE
```

The same works for `Day()`, `Week()` and `Month()` also

**Comment by arjunmahishi** [comment] 2020-09-15 15:19
Hey @graywolf336, 
I am not able to reproduce this with the steps you have mentioned. Is it possible for you to paste the exact snippet of code here?

This is working fine for me:
```go
func main() {
    s := gocron.NewScheduler(time.Local)
    s.Every(3).Seconds().Do(func() {
        log.Println("DONE")
    })  
    log.Println("Starting..")
    <-s.StartAsync()
}
```
Output:
```bash
 $ go run main.go 
2020/09/15 20:46:02 Starting..
2020/09/15 20:46:05 DONE
2020/09/15 20:46:08 DONE
2020/09/15 20:46:11 DONE
```

The same works for `Day()`, `Week()` and `Month()` also

**Comment by graywolf336** [comment] 2020-09-15 15:31
Ah, I am starting the scheduler and then adding the jobs to it after the start was done.

```go
package main

import (
	"log"
	"os"
	"os/signal"
	"sync"
	"time"

	"github.com/go-co-op/gocron"
)

func main() {
	s := gocron.NewScheduler(time.UTC)
	s.StartAsync()

	s.Every(3).Seconds().Do(func() {
		log.Println("DONE")
	})
	log.Println("Starting..")

	waitForCtrlC()
}

func waitForCtrlC() {
	var endWaiter sync.WaitGroup
	endWaiter.Add(1)

	var signalChannel chan os.Signal
	signalChannel = make(chan os.Signal, 1)
	signal.Notify(signalChannel, os.Interrupt)
	go func() {
		<-signalChannel
		endWaiter.Done()
	}()
	endWaiter.Wait()
}
```

Output:
```
$ go run main.go
2020/09/15 10:29:55 Starting..
2020/09/15 10:29:56 DONE
2020/09/15 10:29:59 DONE
2020/09/15 10:30:02 DONE
2020/09/15 10:30:05 DONE
```

**Comment by Streppel** [comment] 2020-09-19 04:20
Oh, right. We are having some problems with jobs being added to the scheduler after it starts but I'll take a look at it over this weekend if possible

**Comment by graywolf336** [comment] 2020-09-19 14:00
@Streppel yeah, that's precisely the case. Thanks for keeping this package maintained! 😊

**Comment by Streppel** [comment] 2020-09-22 00:22
@graywolf336 I believe this has been fixed now.

**Closed by Streppel** 2020-09-22 00:22 UTC
Labels: 3 - done, bug

**Comment by JohnRoesler** [comment] 2021-10-29 18:41
@vojtfa135 what's occurring that isn't expected? Jobs do start immediately by default, except for Cron
